#!/usr/bin/env python3
"""
gen_readme.py — Compute display widths from SVG dimensions and write README.md.

This script reads the viewBox of ascii-portrait.svg and info-card.svg and solves
for the pair of display widths that:
  1. Sum to COMBINED_W (850 px)
  2. Make both images display at the same height

The formula (from the spec):
    portrait_display_w = COMBINED_W * portrait_aspect / (portrait_aspect + card_aspect)
    card_display_w     = COMBINED_W * card_aspect    / (portrait_aspect + card_aspect)
    where aspect = svg_w / svg_h

This is rerun whenever the card's row count changes (which changes SVG height).
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT         = Path(__file__).parent.parent   # repo root
PORTRAIT_SVG = ROOT / "ascii-portrait.svg"
CARD_SVG     = ROOT / "info-card.svg"
HEATMAP_SVG  = ROOT / "contrib-heatmap.svg"
README_OUT   = ROOT / "README.md"

COMBINED_W   = 850
HEATMAP_W    = 860

USERNAME = "saumil-777"


def read_viewbox(path: Path) -> tuple[float, float]:
    """Return (width, height) from the SVG viewBox attribute."""
    try:
        tree = ET.parse(path)
    except (ET.ParseError, FileNotFoundError) as exc:
        print(f"Cannot read {path}: {exc}")
        sys.exit(1)
    vb = tree.getroot().get("viewBox", "")
    parts = vb.split()
    if len(parts) == 4:
        return float(parts[2]), float(parts[3])
    # Fallback to width/height attributes
    w = float(tree.getroot().get("width", "0"))
    h = float(tree.getroot().get("height", "0"))
    return w, h


def compute_display_widths() -> tuple[int, int]:
    pw, ph = read_viewbox(PORTRAIT_SVG)
    cw, ch = read_viewbox(CARD_SVG)

    if ph == 0 or ch == 0:
        print("ERROR: SVG has zero height — cannot compute display widths.")
        sys.exit(1)

    p_aspect = pw / ph   # portrait width-to-height ratio
    c_aspect = cw / ch   # card width-to-height ratio
    total    = p_aspect + c_aspect

    portrait_dw = round(COMBINED_W * p_aspect / total)
    card_dw     = COMBINED_W - portrait_dw   # ensure they sum exactly

    display_h = round(portrait_dw / p_aspect)

    print(f"  Portrait SVG: {pw:.0f}×{ph:.0f}  aspect={p_aspect:.3f}")
    print(f"  Card SVG:     {cw:.0f}×{ch:.0f}  aspect={c_aspect:.3f}")
    print(f"  Display widths:  portrait={portrait_dw}  card={card_dw}  (height≈{display_h}px)")
    return portrait_dw, card_dw


def write_readme(portrait_dw: int, card_dw: int) -> None:
    readme = f"""\
<!--
  README.md — auto-generated by scripts/gen_readme.py
  Do not edit this file by hand.  Run generate_all.py to regenerate.

  Layout rules that work on GitHub:
    · <h1>/<h2> draw a full-width rule — use <h3> for unlined headings.
    · inline style= is stripped from README HTML — layout via <table> and <br>.
    · <table> is the only reliable two-column layout.
    · valign="top" aligns panels to the top of the table cell.
    · SVGs are served as <img> — no JS, no CSS vars, animations via SMIL/keyframes.
-->

<div align="center">

<h3>⬛ &nbsp; {USERNAME} &nbsp; ⬛</h3>

<img src="contrib-heatmap.svg" width="{HEATMAP_W}" alt="Contribution heatmap — 53-week calendar" />

<br><br>

<table>
<tr>
<td valign="top">
<img src="ascii-portrait.svg" width="{portrait_dw}" alt="ASCII portrait" />
</td>
<td valign="top">
<img src="info-card.svg" width="{card_dw}" alt="Info card" />
</td>
</tr>
</table>

<br>

<a href="https://www.linkedin.com/in/saumil-singhal-02a424227/">
  <img src="https://img.shields.io/badge/LinkedIn-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn" />
</a>
&nbsp;
<a href="mailto:singhalsaumil2005@gmail.com">
  <img src="https://img.shields.io/badge/Gmail-EA4335?style=for-the-badge&logo=gmail&logoColor=white" alt="Gmail" />
</a>
&nbsp;
<a href="https://leetcode.com/u/Saumil_Singhal/">
  <img src="https://img.shields.io/badge/LeetCode-FFA116?style=for-the-badge&logo=leetcode&logoColor=white" alt="LeetCode" />
</a>

</div>
"""
    README_OUT.write_text(readme, encoding="utf-8")
    print(f"[readme] Written -> {README_OUT}")


def main() -> None:
    print("\n[readme] Computing display widths ...")
    portrait_dw, card_dw = compute_display_widths()
    write_readme(portrait_dw, card_dw)
    print("[readme] OK Done.")


if __name__ == "__main__":
    main()
